#! /bin/bash

for case in 1 2 3 4
do
    echo $case | tee -a result/train/continual_mnist.txt
    python train_mnist.py --case=$case| tee -a result/train/continual_mnist.txt
done

for case in 1 2 3 4
do
    echo $case | tee -a result/eval/eval_continual_DM.txt
    python evaluate_mnist.py --case=$case --lambda-adv=$lambda --gan=$gan | tee -a result/eval/eval_continual_DM.txt
done

