#! /bin/bash


for lambda in 0.001
do
    echo $lambda | tee -a result/train_source_only_001.txt
    CUDA_VISIBLE_DEVICES=1 python train.py --lambda-adv=$lambda| tee -a result/train_source_only_001.txt
done


