#! /bin/bash

#for case in 1 2 3 4
#do
#    echo $case | tee -a result/train_dann.txt
#    python train_mnist_dann.py --case=$case | tee -a result/train_dann.txt
#done


for case in 1 2 3 4
do
    echo $case | tee -a result/eval_dann.txt
    python evaluate_dann.py --case=$case | tee -a result/eval_dann2.txt
done



