#! /bin/bash

for gan in Hinge; do
    for case in 1; do
        for lambda in 0.5 1.0 2.0 2.5 3.0 3.5 4.0 5.0 6.0; do
            echo $case | tee -a result/train/mnist_DM.txt
            python train_mnist_DM.py --case=$case --lambda-adv=$lambda --gan=$gan | tee -a result/train/mnist_DM.txt
        done

        for lambda in 0.5 1.0 2.0 2.5 3.0 3.5 4.0 5.0 6.0; do
            echo $case $gan $lambda | tee -a result/eval/eval_DM_UDA.txt
            python evaluate_mnist.py --case=$case --lambda-adv=$lambda --gan=$gan | tee -a result/eval/eval_DM_UDA.txt
        done
    done
done

